[17:59:09] ✅ Connected to database sqlite:////home/thalles/Documentos/ProjetosGit/Estudo_DeepSeek_Ollma/API/db/api_logs.db
[17:59:15] ✅ Servidor iniciado com sucesso na porta 5000
[17:59:15] ✅ Running on http://0.0.0.0:5000 (CTRL + C to quit)
[18:00:53] ✅ Disconnected from database sqlite:////home/thalles/Documentos/ProjetosGit/Estudo_DeepSeek_Ollma/API/db/api_logs.db
[18:00:55] ✅ Connected to database sqlite:////home/thalles/Documentos/ProjetosGit/Estudo_DeepSeek_Ollma/API/db/api_logs.db
[18:01:11] ✅ Servidor iniciado com sucesso na porta 5000
[18:01:11] ✅ Running on http://0.0.0.0:5000 (CTRL + C to quit)
[18:07:40] ⛔ Erro inesperado: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[18:07:41] ⛔ Erro inesperado: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[18:07:44] ⛔ Erro inesperado: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[18:07:44] ⛔ Erro inesperado: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[18:09:25] ✅ Disconnected from database sqlite:////home/thalles/Documentos/ProjetosGit/Estudo_DeepSeek_Ollma/API/db/api_logs.db
[18:09:26] ✅ Connected to database sqlite:////home/thalles/Documentos/ProjetosGit/Estudo_DeepSeek_Ollma/API/db/api_logs.db
[18:09:38] ✅ Servidor iniciado com sucesso na porta 5000
[18:09:38] ✅ Running on http://0.0.0.0:5000 (CTRL + C to quit)
[18:09:59] ⛔ Erro inesperado: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[18:09:59] ⛔ Erro inesperado: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[18:09:59] ⛔ Task exception was never retrieved
future: <Task finished name='Task-19' coro=<shutdown_and_exit() done, defined at /home/thalles/Documentos/ProjetosGit/Estudo_DeepSeek_Ollma/API/api_deepseek.py:218> exception=SystemExit(1)>
[18:11:45] ✅ Connected to database sqlite:////home/thalles/Documentos/ProjetosGit/Estudo_DeepSeek_Ollma/API/db/api_logs.db
[18:12:06] ✅ Servidor iniciado com sucesso na porta 5000
[18:12:06] ✅ Running on http://127.0.0.1:5000 (CTRL + C to quit)
[18:12:12] ⛔ Erro inesperado: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[18:12:12] ⛔ Erro inesperado: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[18:12:12] ⛔ Task exception was never retrieved
future: <Task finished name='Task-19' coro=<shutdown_and_exit() done, defined at /home/thalles/Documentos/ProjetosGit/Estudo_DeepSeek_Ollma/API/api_deepseek.py:218> exception=SystemExit(1)>
